import { Document, HeadingLevel, Packer, Paragraph, TextRun } from 'docx'
import fs from 'node:fs/promises'
import path from 'node:path'

async function writeFixture() {
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({ text: 'Heading 1', heading: HeadingLevel.HEADING_1 }),
          new Paragraph({ children: [new TextRun('This is a fixture generated by scripts/make-fixtures.ts.')] }),
          new Paragraph({ text: 'Heading 2', heading: HeadingLevel.HEADING_2 })
        ]
      }
    ]
  })

  const buffer = await Packer.toBuffer(doc)
  const fixtureDir = path.resolve(process.cwd(), 'tests/fixtures')
  await fs.mkdir(fixtureDir, { recursive: true })
  await fs.writeFile(path.join(fixtureDir, 'm3-docx.docx'), Buffer.from(buffer))
  console.log('Wrote', path.join(fixtureDir, 'm3-docx.docx'))
}

void writeFixture()
